#!/bin/bash 

# usage: $0 $1
#   $1 .. number of car
#   stdin .. fuel string (use "s)

POSTCONTENT=$(echo $(cat | sed -r 's#$#%0D%0A#') | sed 's# ##g')

[ -f ~/cookies.txt ] || {
  echo "i need cookies.txt in homedir, use firefox extension cookie export"
  exit 1
}

TEMPF=$(mktemp)

wget --load-cookies ~/cookies.txt -O $TEMPF --post-data 'contents='"$POSTCONTENT" http://icfpcontest.org/icfp10/instance/$1/solve || {
     echo wget failed
     exit 1
}

echo $2
echo Fehlermeldung:

sed 's#>#>\n#g' < $TEMPF | awk '{if (outputon) {print}} /<pre>/ { outputon=1 } /<[/]pre>/ { outputon=0}' | sed 's#</pre>##' > log/$POSTCONTENT-errormsg.txt
cat log/$POSTCONTENT-errormsg.txt

echo Done

cp $TEMPF last-wget.html

rm -f $TEMPF

exit 0